### PR TITLE
Corrects tiny typo in conflicting lockfile failure message

### PR DESCRIPTION
**Pull request by BigAlUK**
Just a very small typo fix.

### CODE REVIEW

**Comment by danielleadams** [comment]
Thanks @BigAlUK! Mind updating the CHANGELOG too?

**Comment by danielleadams** [comment]
`main` is actually broken right now (been working to fix it), so once it's fixed I can rebase for you

**Comment by edmorley** [comment]
@BigAlUK Sorry for the churn - I don't suppose you could rebase on `main` and we'll make sure it gets merged before it conflicts this time? :-)

**Comment by BigAlUK** [comment]
@edmorley I think it's rebased up to main now.

**Comment by edmorley** [comment]
@joshwlewis CI is failing with:

```
ASSERT:Expected </tmp/tmp.zHnCba0e4H> to contain <resolve-v1-yarn="1.22.10 https://s3.amazonaws.com/heroku-nodebin/yarn/release/yarn-v1.22.10.tar.gz">
ASSERT:Expected </tmp/tmp.zHnCba0e4H> to contain <resolve-is-equal-yarn=true>
```

This comes from:
https://github.com/heroku/heroku-buildpack-nodejs/blob/70af8362fb5d2c924a88beb0e837ee77804f67b6/test/run#L1304-L1306

A new version of Yarn was released 2 weeks ago:
https://github.com/yarnpkg/yarn/releases/tag/v1.22.11

It looks like the test fixture for this test doesn't pin the version of Yarn, which is why it's now failing:
https://github.com/heroku/heroku-buildpack-nodejs/blob/d3b484a2ee38e08500c172c8da17a624b7db4374/test/fixtures/pre-post-build-scripts/package.json#L9-L11

Mind if I leave it to you to fix this and then land this PR? :-)

**Comment by joshwlewis** [comment]
Sure, I'll take a look. Thanks.

**Comment by joshwlewis** [comment]
@BigAlUK I've fixed the issues with CI on the `main` branch. Would you mind rebasing this PR against, so we can get this all green and merged?

**Comment by edmorley** [comment]
@joshwlewis I triggered CI for this hoping it could be merged, but there appears to be another failure on `main` again. Seems like this repo is using old Hatchet (no dependabot) which is still using the APT install method for the Heroku CLI, which is failing for some reason:
https://app.circleci.com/pipelines/github/heroku/heroku-buildpack-nodejs/292/workflows/8516bef5-4011-41d0-980a-a3bcb5547308/jobs/2009

**Review by joshwlewis — APPROVED** [review]
The tests were fixed in the main branch, so I took the liberty to rebase this PR. Thanks for the fix!

**Pull request merged**
