### PR TITLE
Added heroku prebuild and postbuild scripts

### LINKED ISSUE #269: Should the buildpack provide an arbitrary pre-build hook?
For the most part, node's lifecycle scripts work well for running things before / after installs, before start, etc.

However, in some cases it would be useful to be able to modify things like .npmrc files ahead of time (since changes to those files won't be recognized from inside of the npm scripts).

### PR DESCRIPTION
**Pull request by fiznool**
Fixes #269

### CODE REVIEW

**Comment by jbcpollak** [comment]
Any chance this change could be merged it? I've been using it and it works well.

**Comment by hunterloftis** [comment]
@jbcpollak it will be merged this week

**Comment by fiznool** [comment]
Thanks @hunterloftis, your simplifications are great, my bash-foo needs work ☺

**Comment by hunterloftis** [comment]
:+1: 
Save yourself, spend as little time in bash as you can get away with!

**Pull request merged**
