### PR TITLE
Avoid using proxy

### PR DESCRIPTION
**Pull request by tt**

### CODE REVIEW

**Comment by zeke** [comment]
Hi, @tt!

Why?

**Comment by tt** [comment]
We want to retire the proxy component and it's not evident that we need it here which the pull request is an experiment for figuring out.

The `install_iojs` function in the same file always downloaded from https://iojs.org/ directly and that didn't cause any issues.

**Comment by zeke** [comment]
I see. Is it a burden to keep the proxy alive? There were a few instances back in the day when nodejs.org went down and Heroku deployments stayed up. Our customers noticed and were happy about it.

**Comment by hunterloftis** [comment]
Currently the proxy is written in Scala and maintained just for the node bp; plan is to basically add a proxy / s3 caching layer to the semver service so it can report versions and also serve the versions it reports.

@tt just wants to just down s3pository asap ;)

**Comment by zeke** [comment]
> add a proxy / s3 caching layer to the semver service so it can report versions and also serve the versions it reports

🎉

**Comment by hunterloftis** [comment]
Closing as this will soon be replaced by the nodebin service.

**Pull request closed without merging**
