### PR TITLE
Solving no such file or directory error

### PR DESCRIPTION
**Pull request by viniciustrindade**
```
 Error:
```

```
    events.js:154
       throw er; // Unhandled 'error' event
       ^

       Error: ENOENT: no such file or directory, open '/tmp/build_bb3s1b098832350ad59f717e152044/c366f7b46c418scf01bf5c0fa56a3715d3c7c01//tmp/node-build-log.txt'
       at Error (native)
       [13:44:19] [nodemon] app crashed - waiting for file changes before starting...

```

### CODE REVIEW

**Comment by hunterloftis** [comment]
This would store the build log (including anything sensitive that it outputs, like api keys etc) in the slug. We can't undermine security like that - if we're going to move the temp directory, it needs to still be outside of the slug.

I also haven't seen reports of such an error and node build failures are in a normal range at the moment.

**Comment by hunterloftis** [comment]
If you'd like to continue with this though, we could make it more dynamic (eg, via `mktemp`)

**Comment by viniciustrindade** [comment]
OK I will use the mktemp command and push it at soon.

**Comment by hunterloftis** [comment]
The current master branch uses `mktemp`, heading to the /tmp directory on Heroku (outside of the slug).

**Pull request closed without merging**
