### PR TITLE
Allow custom build script

### PR DESCRIPTION
**Pull request by Aulos**
Useful for monorepos and yarn workspaces.

### CODE REVIEW

**Comment by jmorrell** [comment]
Hi @Aulos 

I want to move away from using ENV vars to configure the buildpack, but I'm curious as to what your motivation is here? How is this different than adding a `build` script to `package.json`? https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process

**Comment by Aulos** [comment]
I'm using yarns workspaces, so in the main package I have `build-package1`
and `build-package2`. They both are separate heroku apps and one `build`
command wouldn't cut it. (I additionally use a small buildpacks to copy
package procfile to build_dir)

I know there are buildpacks for workspaces, but usually they copy content
of a package to build_dir what is not how you usually use workspaces. My
solution seemed much less intrusive.

wt., 9 lip 2019, 02:31 użytkownik Jeremy Morrell <notifications@github.com>
napisał:

**Comment by jmorrell** [comment]
@Aulos 🤔  You could still use an env var to specify your command by using it in the `build` script without modifying the buildpack. I believe the following would work:

```
"scripts": {
  "build": "bash $CUSTOM_BUILD_COMMAND"
}
```

or factor out your build commands into a script that does things based on an env var.

You might also be interested in the discussions in this thread: https://github.com/heroku/heroku-buildpack-nodejs/issues/385#issuecomment-420069304

**Comment by Aulos** [comment]
Thanks, I'll try it 😃

**Pull request closed without merging**
