### PR TITLE
allow skipping node_modules removal with SKIP_NODE_MODULES_CHECK

### PR DESCRIPTION
**Pull request by llhupp**
Based on my issue here: https://github.com/heroku/heroku-buildpack-nodejs/issues/797

### CODE REVIEW

**Comment by danielleadams** [comment]
Hi @llhupp, I left a comment on the issue - I think I need a little more information on the motivation of this change before we move forward. Thanks!

**Comment by danielleadams** [comment]
Can I close this in favor of https://github.com/heroku/heroku-buildpack-nodejs/pull/795?

**Comment by danielleadams** [comment]
Fixes: https://github.com/heroku/heroku-buildpack-nodejs/issues/797

@llhupp can you rebase this? Afterwards, I'll run some tests locally and see if we need to do anything else, but it looks good to go 😄 thanks again!

**Comment by llhupp** [comment]
will do!

**Comment by llhupp** [comment]
Glad I could contribute!

**Pull request merged**
