### PR TITLE
Add $STACK to the cache signature

### LINKED ISSUE #445: Cache not cleared after changing stacks
I just switched an app from cedar-14 to heroku-16 and the first build thereafter reused the existing `node_modules` directory:
```
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.27.5
       [1/4] Resolving packages...
       success Already up-to-date.
       Done in 1.34s.
```

This seems risky for packages that contain compiled code.

As such, I think it would be good to include `$STACK` in the cache signature here:
https://github.com/heroku/heroku-buildpack-nodejs/blob/da19bdb738fb1ee3ea183ba0a7dd4695843ee383/lib/cache.sh#L3-L5

### PR DESCRIPTION
**Pull request by edmorley**
To ensure that the cache is busted when apps update to a new stack.

Fixes #445.

### CODE REVIEW

**Comment by edmorley** [comment]
I meant to add:

Trying to end-to-end test this change by installing under one stack and then checking the cache isn't restored would require a significant rework of the current tests. Since we already have tests that confirm changing the signature successfully busts the cache, it seems sufficient to just test that the signature now does contain the stack - though let me know if you would prefer this tested in another way :-)

**Comment by jmorrell** [comment]
Docs for the `$STACK` env variable: https://devcenter.heroku.com/articles/buildpack-api#stacks

**Comment by jmorrell** [comment]
Thanks for all the great contributions @edmorley! :)

**Comment by jmorrell** [comment]
Trying to test this by actually switching the stacks would be way too complex and heavy for little gain. This works nicely 👌

**Pull request merged**
