### PR TITLE
Support running on OSX

### PR DESCRIPTION
**Pull request by focusaurus**
- switch from jq binary to https://github.com/dominictarr/JSON.sh
- detect current OS and CPU at runtime instead of hard coding linux x64

This works and passes all of the cedar-14 tests most of the cedar tests but the failing ones also fail in the master branch so I'm confident the failures are unrelated to these changes.

It's not entirely clear to me the purpose of `warnings=$(mktemp)` so clarification/help on that one is welcome.

### CODE REVIEW

**Comment by focusaurus** [comment]
Should help with #226

**Comment by hunterloftis** [comment]
@focusaurus thanks! I'll take a look at this as soon as I can. Running on osx isn't high priority, but it's a *definite* nice to have so I appreciate you not only opening an issue but also submitting a PR.

**Comment by focusaurus** [comment]
Thanks! I realize this may be scope creek and you may want to focus on the heroku-specific use case, but AFAIK there's no better candidate in the npm ecosystem than this repo for "this is the normal way to build a node repo from source to runnable". I'd love to see this become something used more broadly, but a separate project might also make sense, perhaps working with nvm.sh.

**Comment by hunterloftis** [comment]
Pretty awesome to be able to run this stuff cross-platform! Executing `test/run` under osx I get a few errors:

```
testNodeModulesCached
ASSERT:expected:<1> but was:<       1>
ASSERT:expected:<1> but was:<       1>
testBuildWithCache
testBuildWithUserCacheDirectories
ASSERT:expected:<1> but was:<       1>
ASSERT:expected:<1> but was:<       1>
ASSERT:Expected captured exit code to be 0; was <1> expected:<0> but was:<1>
testBuildWithUserCacheDirectoriesCamel
ASSERT:expected:<1> but was:<       1>
ASSERT:expected:<1> but was:<       1>
ASSERT:Expected captured exit code to be 0; was <1> expected:<0> but was:<1>
```

**Comment by focusaurus** [comment]
OK quick look points to maybe OSX `wc -l` printing some leading indentation:

    echo foo | wc -l| cat -vet
       1$

If that is the case this should be an easy fix.

**Comment by hunterloftis** [comment]
Yeah except for the couple of 0=>1s it looked like formatting.

**Comment by focusaurus** [comment]
The other issue is probably 2 instances of the same thing. Something with cacheing node_modules isn't working right. Investigating...

**Comment by focusaurus** [comment]
So I think the second `bin/compile` run in `testBuildWithUserCacheDirectories` is failing. I dug around to find the `stdout` file and found this post-install bower script error. Have you seen this before?


       > node-buildpack-test-app@0.0.1 postinstall /private/var/folders/6f/cw1_bc_960n35_yvvv1tvbr40000gn/T/testXXXXX.dq8SXyAD
       > bower install --allow-root


       module.js:340
           throw err;
                 ^
       Error: Cannot find module 'q'
           at Function.Module._resolveFilename (module.js:338:15)
           at Function.Module._load (module.js:280:25)
           at Module.require (module.js:364:17)
           at require (module.js:380:17)
           at Object.<anonymous> (/private/var/folders/6f/cw1_bc_960n35_yvvv1tvbr40000gn/T/testXXXXX.dq8SXyAD/node_modules/.bin/bower:6:9)
           at Module._compile (module.js:456:26)
           at Object.Module._extensions..js (module.js:474:10)
           at Module.load (module.js:356:32)
           at Function.Module._load (module.js:312:12)
           at Function.Module.runMain (module.js:497:10)
       npm ERR! weird error 8
       npm ERR! not ok code 0

I'm not sure what to make of this yet. When I manually run the revelant commands by hand, they work fine.

**Comment by focusaurus** [comment]
For some reason `./node_modules/.bin/bower` is a regular file instead of being a symlink to `./node_modules/bower/bin/bower` and that seems to be screwing up the `require` search path.

**Comment by focusaurus** [comment]
OK @hunterloftis the tests pass on OSX and cedar-14 now . cedar-10 is mostly good except the `testUnstableVersion` below but I think these same issues occur in `master`.

    ASSERT:Expected captured exit code to be 0; was <1> expected:<0> but was:<1>
    ASSERT:Expected STD_ERR to be empty; was </tmp/testtdgLN/.heroku/node/bin/node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /tmp/testtdgLN/.heroku/node/bin/node)
    node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by node)
    /tmp/testtdgLN/.heroku/node/bin/node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /tmp/testtdgLN/.heroku/node/bin/node)> expected:<> but was:</tmp/testtdgLN/.heroku/node/bin/node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /tmp/testtdgLN/.heroku/node/bin/node)
    node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by node)
    /tmp/testtdgLN/.heroku/node/bin/node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /tmp/testtdgLN/.heroku/node/bin/node)>

**Comment by hunterloftis** [comment]
@focusaurus nicely debugged! I'll pull this down this upcoming week and go over it once more. I'm merging it slowly and cautiously because it touches several files in non-trivial ways, but it's super cool!

**Comment by hunterloftis** [comment]
squashed into https://github.com/heroku/heroku-buildpack-nodejs/pull/236

**Pull request closed without merging**
