### PR TITLE
Skip yarn install if binary found at .yarn/releases

### PR DESCRIPTION
**Pull request by llhupp**
This skips installing yarn if it is already provided in the source. My team's projects include yarn in the bundles that are deployed to Heroku, so there shouldn't be a need to install it globally. See [yarn policies](https://classic.yarnpkg.com/en/docs/cli/policies/#toc-policies-set-version) for more info.

### CODE REVIEW

**Comment by danielleadams** [comment]
Hi @llhupp, in order to use the installed yarn, at the current time Yarn 1 needs to be installed. I checked with the Yarn team and this is the best way to use a vendored Yarn 2, but they are still working on not needing to install Yarn 1 to use it.

**Comment by llhupp** [comment]
Hey @danielleadams, that's interesting. It seems to install packages just fine and I would assume it runs scripts just fine as well. But, if the team says there is weird behavior or potential issues if Yarn is not installed globally, would you mind if I added a flag like `USE_UNSAFE_LOCAL_YARN` to allow this until the Yarn team deems it more stable?

**Comment by llhupp** [comment]
To go along with [my comment on a similar issue](https://github.com/heroku/heroku-buildpack-nodejs/issues/797#issuecomment-656816441), I'm fine with shelving this work and adapting it for yarn2 at a later date if it's not already resolved by their install strategy.

**Comment by danielleadams** [comment]
@llhupp great. Thanks! I will go ahead and close this if that's okay?

**Comment by danielleadams** [comment]
Solved with https://github.com/heroku/heroku-buildpack-nodejs/pull/795

**Comment by danielleadams** [comment]
Going to close this since https://github.com/heroku/heroku-buildpack-nodejs/pull/795 has been released.

**Pull request closed without merging**
