### PR TITLE
add 10.23.3, 12.20.2 and 14.5.5 to inventory

### PR DESCRIPTION
**Pull request by danielleadams**
Update local inventory for next node versions

### CODE REVIEW

**Review by edmorley — CHANGES_REQUESTED** [review]
Travis and check changelog are failing

**Comment by danielleadams** [comment]
`main` is failing so I'm going to convert this back to draft to figure out what's going on

**Comment by danielleadams** [comment]
@edmorley fixed the tests on the base branch. I think these should hopefully pass now!

**Review by edmorley — APPROVED** [review]
🎉

**Pull request merged**
