### PR TITLE
Fix some Bash issues

### PR DESCRIPTION
**Pull request by Androbin**
Use `"${var:?}"` to ensure this never expands to `/*` .
Double quote array expansions, otherwise they're like `$*` and break on spaces.
Argument mixes string and array. Use `*` or separate argument.

### CODE REVIEW

**Comment by dzuelke** [comment]
This actually only catches a few unquoted spots (for `$dir`, for instance). I also think it's better to catch the unset/empty case early, in the `local dir="$1"` assignment.

The `$@` quoting stuff is definitely necessary to avoid breakage when elements contain spaces.

**Comment by Androbin** [comment]
@dzuelke If you wanna look into it, this is [a complete list of quoting issues](https://pastebin.com/kdxxxeBn).
I will amend a commit to catch the unset/empty case early as you suggested.

**Comment by jmorrell** [comment]
Apologies for closing without comment!

This may be better bash, but it results in many failing tests: https://travis-ci.org/heroku/heroku-buildpack-nodejs/jobs/359974199 that make this difficult to merge

**Comment by Androbin** [comment]
I reverted the changes to `test/shunit2`.
But I just can't figure out what breaks the build...

**Comment by Androbin** [comment]
@jmorrell I've run the tests on current `master` and get the same errors.

**Comment by jmorrell** [comment]
@Androbin There is a failing yarn cache test on master which is fixed by: https://github.com/heroku/heroku-buildpack-nodejs/pull/551 but the rest should pass

**Comment by jmorrell** [comment]
Ah, that's the only build that's failing now :D Once that is merged I can merge this then

**Comment by jmorrell** [comment]
@Androbin can you rebase this change off of master? That should let CI pass

**Comment by Androbin** [comment]
Done

**Comment by jmorrell** [comment]
Merged! Thank you for the fixes 🙏 and sorry for closing the PR 🙈

**Pull request merged**
