### PR TITLE
Add unit tests around WEB_CONCURRENCY

### PR DESCRIPTION
**Pull request by michaelherold**
This buildpack is inconsistent with [the heroku/ruby buildpack's setting
of WEB_CONCURRENCY][1]. It tries to guess a reasonable value for
WEB_CONCURRENCY, even if one is set manually in the application's
configuration.

Since this value is used, by default, [by the Puma web server][2], this
behavior is undesirable. Newer Rails applications use both the
heroku/nodejs buildpack and the heroku/ruby buildpack because Rails
manages assets through Webpack.

This change respects any value that the customer sets for
WEB_CONCURRENCY via `heroku config:set` instead of blindly overwriting
the value. With this behavior, the customer can better control the
process-level concurrency for their applications.

I verified that this behavior does, indeed, occur by doing the
following:

1. `heroku config:set WEB_CONCURRENCY=2 -a <myapp>`
2. `heroku run -a <myapp> bash`
3. `echo $WEB_CONCURRENCY`

For step (3), the value was set to `WEB_CONCURRENCY=1` instead of the
expected `WEB_CONCURRENCY=2`. I do not believe the buildpacks have an
order-dependence since the Ruby one does not override a set value.

[1]: https://github.com/heroku/heroku-buildpack-ruby/blob/ff7927dc5f93d89a45683895ac157d739bfbb2f1/lib/language_pack/ruby.rb#L321-L344
[2]: https://github.com/puma/puma/blob/c13829c258034dbe6511c5e60604b7546e125d19/lib/puma/configuration.rb#L195

### CODE REVIEW

**Comment by michaelherold** [comment]
It appears my understanding of what environment variables are set when you run a `ps:exec` was flawed. I see that none of the environment variables that you set in your application configuration are available. Thus, the unexpected behavior I was seeing wasn't correct.

I understand if this change isn't wanted, but it would be nice to see consistent behavior between different Heroku-created buildpacks. To me, the setting of the value unless it is already set leads to more understandability.

**Comment by dzuelke** [comment]
This is already the behavior: https://github.com/heroku/heroku-buildpack-nodejs/blob/664de44b8019ce7a7dfd64e6ea86c02cf06aabdb/profile/WEB_CONCURRENCY.sh#L8 sets the variable to the user-supplied value, then performs some sanity checks (too large or too small) on it.

Maybe keep the unit tests, they can't hurt, and remove the other two changes? ;)

**Comment by danielleadams** [comment]
@michaelherold Thanks for the PR! As @dzuelke said, the extra coverage would be great if you could fix the tests. Otherwise, do you mind if we close this?

**Comment by michaelherold** [comment]
> This is already the behavior:

🤦 So it is. It was very easy to miss that since it's hidden in the function. And since it does some checking against the value, my sentinel value was being ignored.

> the extra coverage would be great if you could fix the tests. 

I removed everything but the tests, but Hatchet is still failing to work correctly on CI. I don't know why that's happening.

**Comment by danielleadams** [comment]
@michaelherold These are tests that we run internally to check integration with the Heroku platform. I recently moved the tests to Circle CI where I am not able to figure out how to run the test myself (they will continue to fail because you don't have access to the Heroku creds). If I can't figure this out, I'll open a pull request a run the tests on the next release. Thanks!

**Review by danielleadams — APPROVED** [review]

**Comment by danielleadams** [comment]
@michaelherold Can you rebase this? I can merge it it once it matches the base branch. Thanks!

**Comment by danielleadams** [comment]
@michaelherold can you rebase this?

**Comment by michaelherold** [comment]
Done!

**Pull request merged**
