### PR TITLE
Prepare release v234

### PR DESCRIPTION
**Pull request by joshwlewis**
This will release Node.js 20.11.0 under the v234 tag.

### CODE REVIEW

**Comment by schinery** [comment]
@joshwlewis do you know when this update might be released?

**Comment by colincasey** [comment]
@schinery this update will be released in the next couple of hours. I'm just waiting for #1195 to merge so that Node 21.6.0 will also be included.

**Comment by schinery** [comment]
Awesome, thanks @colincasey 👍🏻

**Comment by colincasey** [comment]
@schinery release `v234` is now available.

**Pull request merged**
